/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t font_3x5_raw[];
extern const uint8_t font_3x5_raw_end[];
#if __cplusplus >= 201103L
static constexpr size_t font_3x5_raw_size=42;
#else
static const size_t font_3x5_raw_size=42;
#endif
