/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t icon_flp_raw[];
extern const uint8_t icon_flp_raw_end[];
#if __cplusplus >= 201103L
static constexpr size_t icon_flp_raw_size=41;
#else
static const size_t icon_flp_raw_size=41;
#endif
