/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t nitrotracker_logo_raw[];
extern const uint8_t nitrotracker_logo_raw_end[];
#if __cplusplus >= 201103L
static constexpr size_t nitrotracker_logo_raw_size=340;
#else
static const size_t nitrotracker_logo_raw_size=340;
#endif
