/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t sampleedit_loop_icon_raw[];
extern const uint8_t sampleedit_loop_icon_raw_end[];
#if __cplusplus >= 201103L
static constexpr size_t sampleedit_loop_icon_raw_size=16;
#else
static const size_t sampleedit_loop_icon_raw_size=16;
#endif
