/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t sampleedit_all_raw[];
extern const uint8_t sampleedit_all_raw_end[];
#if __cplusplus >= 201103L
static constexpr size_t sampleedit_all_raw_size=22;
#else
static const size_t sampleedit_all_raw_size=22;
#endif
