/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t haken_raw[];
extern const uint8_t haken_raw_end[];
#if __cplusplus >= 201103L
static constexpr size_t haken_raw_size=13;
#else
static const size_t haken_raw_size=13;
#endif
